# apiVersion: v1
# kind: Pod
# metadata:
#   name: nginx-Pod
#   namespace: roboshop
#   labels:
#     app: nginx
#     env: dev
# spec:
#   containers:
#   - name: nginx
#   image: nginx
#   ports:
#   - containerport: 80
#   imagepullpolicy: IfNotPresent

apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: roboshop
  labels:
    app: nginx
    env: dev
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    imagePullPolicy: IfNotPresent