apiVersion: v1
kind: Pod
metadata:
  name: frontend1
  namespace: roboshop
  labels:
    app: frontend
    version: v1
    environment: production
    tier: web
spec:
  containers:
  - name: frontend
    image: nginx
