apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: roboshop
spec:
  type: NodePort   # 👈 IMPORTANT
  selector:
    app: frontend
    environment: production
  ports:
  - port: 80
    # targetPort: 3000
    nodePort: 30007   # optional (range: 30000–32767)