apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: roboshop
spec:
  type: ClusterIP
  selector:
    project: roboshop
    component: frontend
    environment: dev
  ports:
  - protocol: TCP
    port: 80 # servie port
    targetPort: 80 # container port
